export type Property = {
    id: number;
    slug: string;
    title: string;
    location: string;
    price: number;
    bedrooms: number;
    bathrooms: number;
    area: number;
    type: string;
    for_rent: boolean;
    image: string;
    images: string[];
    description: string;
    features: string[];
    amenities: string[];
}

const properties: Property[] = [
    {
        "id": 1,
        "slug": "property-1",
        "title": "Property Title 1",
        "location": "Location 1",
        "price": 11000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area": 3200,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 1.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 2,
        "slug": "property-2",
        "title": "Property Title 2",
        "location": "Location 2",
        "price": 12000,
        "bedrooms": 5,
        "bathrooms": 4,
        "area": 3400,
        "type": "apartment",
        "for_rent": true,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 2.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 3,
        "slug": "property-3",
        "title": "Property Title 3",
        "location": "Location 3",
        "price": 13000,
        "bedrooms": 6,
        "bathrooms": 5,
        "area": 3600,
        "type": "villa",
        "for_rent": false,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 3.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 4,
        "slug": "property-4",
        "title": "Property Title 4",
        "location": "Location 4",
        "price": 14000,
        "bedrooms": 7,
        "bathrooms": 6,
        "area": 3800,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 4.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 5,
        "slug": "property-5",
        "title": "Property Title 5",
        "location": "Location 5",
        "price": 15000,
        "bedrooms": 8,
        "bathrooms": 7,
        "area": 4000,
        "type": "apartment",
        "for_rent": false,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 5.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 6,
        "slug": "property-6",
        "title": "Property Title 6",
        "location": "Location 6",
        "price": 16000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area": 4200,
        "type": "villa",
        "for_rent": true,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 6.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 7,
        "slug": "property-7",
        "title": "Property Title 7",
        "location": "Location 7",
        "price": 17000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area": 4400,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 7.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 8,
        "slug": "property-8",
        "title": "Property Title 8",
        "location": "Location 8",
        "price": 18000,
        "bedrooms": 5,
        "bathrooms": 5,
        "area": 4600,
        "type": "apartment",
        "for_rent": true,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 8.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 9,
        "slug": "property-9",
        "title": "Property Title 9",
        "location": "Location 9",
        "price": 19000,
        "bedrooms": 6,
        "bathrooms": 6,
        "area": 4800,
        "type": "villa",
        "for_rent": false,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 9.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 10,
        "slug": "property-10",
        "title": "Property Title 10",
        "location": "Location 10",
        "price": 20000,
        "bedrooms": 7,
        "bathrooms": 7,
        "area": 5000,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 10.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 11,
        "slug": "property-11",
        "title": "Property Title 11",
        "location": "Location 11",
        "price": 21000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area": 5200,
        "type": "apartment",
        "for_rent": false,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 11.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 12,
        "slug": "property-12",
        "title": "Property Title 12",
        "location": "Location 12",
        "price": 22000,
        "bedrooms": 5,
        "bathrooms": 4,
        "area": 5400,
        "type": "villa",
        "for_rent": true,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 12.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 13,
        "slug": "property-13",
        "title": "Property Title 13",
        "location": "Location 13",
        "price": 23000,
        "bedrooms": 6,
        "bathrooms": 5,
        "area": 5600,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 13.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 14,
        "slug": "property-14",
        "title": "Property Title 14",
        "location": "Location 14",
        "price": 24000,
        "bedrooms": 7,
        "bathrooms": 6,
        "area": 5800,
        "type": "apartment",
        "for_rent": true,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 14.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 15,
        "slug": "property-15",
        "title": "Property Title 15",
        "location": "Location 15",
        "price": 25000,
        "bedrooms": 8,
        "bathrooms": 7,
        "area": 6000,
        "type": "villa",
        "for_rent": false,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 15.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 16,
        "slug": "property-16",
        "title": "Property Title 16",
        "location": "Location 16",
        "price": 26000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area": 6200,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 16.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 17,
        "slug": "property-17",
        "title": "Property Title 17",
        "location": "Location 17",
        "price": 27000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area": 6400,
        "type": "apartment",
        "for_rent": false,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 17.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 18,
        "slug": "property-18",
        "title": "Property Title 18",
        "location": "Location 18",
        "price": 28000,
        "bedrooms": 5,
        "bathrooms": 5,
        "area": 6600,
        "type": "villa",
        "for_rent": true,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 18.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 19,
        "slug": "property-19",
        "title": "Property Title 19",
        "location": "Location 19",
        "price": 29000,
        "bedrooms": 6,
        "bathrooms": 6,
        "area": 6800,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 19.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 20,
        "slug": "property-20",
        "title": "Property Title 20",
        "location": "Location 20",
        "price": 30000,
        "bedrooms": 7,
        "bathrooms": 7,
        "area": 7000,
        "type": "apartment",
        "for_rent": true,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 20.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 21,
        "slug": "property-21",
        "title": "Property Title 21",
        "location": "Location 21",
        "price": 31000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area": 7200,
        "type": "villa",
        "for_rent": false,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 21.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 22,
        "slug": "property-22",
        "title": "Property Title 22",
        "location": "Location 22",
        "price": 32000,
        "bedrooms": 5,
        "bathrooms": 4,
        "area": 7400,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 22.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 23,
        "slug": "property-23",
        "title": "Property Title 23",
        "location": "Location 23",
        "price": 33000,
        "bedrooms": 6,
        "bathrooms": 5,
        "area": 7600,
        "type": "apartment",
        "for_rent": false,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 23.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 24,
        "slug": "property-24",
        "title": "Property Title 24",
        "location": "Location 24",
        "price": 34000,
        "bedrooms": 7,
        "bathrooms": 6,
        "area": 7800,
        "type": "villa",
        "for_rent": true,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 24.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 25,
        "slug": "property-25",
        "title": "Property Title 25",
        "location": "Location 25",
        "price": 35000,
        "bedrooms": 8,
        "bathrooms": 7,
        "area": 8000,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 25.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 26,
        "slug": "property-26",
        "title": "Property Title 26",
        "location": "Location 26",
        "price": 36000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area": 8200,
        "type": "apartment",
        "for_rent": true,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 26.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 27,
        "slug": "property-27",
        "title": "Property Title 27",
        "location": "Location 27",
        "price": 37000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area": 8400,
        "type": "villa",
        "for_rent": false,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 27.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 28,
        "slug": "property-28",
        "title": "Property Title 28",
        "location": "Location 28",
        "price": 38000,
        "bedrooms": 5,
        "bathrooms": 5,
        "area": 8600,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 28.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 29,
        "slug": "property-29",
        "title": "Property Title 29",
        "location": "Location 29",
        "price": 39000,
        "bedrooms": 6,
        "bathrooms": 6,
        "area": 8800,
        "type": "apartment",
        "for_rent": false,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 29.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 30,
        "slug": "property-30",
        "title": "Property Title 30",
        "location": "Location 30",
        "price": 40000,
        "bedrooms": 7,
        "bathrooms": 7,
        "area": 9000,
        "type": "villa",
        "for_rent": true,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 30.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 31,
        "slug": "property-31",
        "title": "Property Title 31",
        "location": "Location 31",
        "price": 41000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area": 9200,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 31.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 32,
        "slug": "property-32",
        "title": "Property Title 32",
        "location": "Location 32",
        "price": 42000,
        "bedrooms": 5,
        "bathrooms": 4,
        "area": 9400,
        "type": "apartment",
        "for_rent": true,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 32.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 33,
        "slug": "property-33",
        "title": "Property Title 33",
        "location": "Location 33",
        "price": 43000,
        "bedrooms": 6,
        "bathrooms": 5,
        "area": 9600,
        "type": "villa",
        "for_rent": false,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 33.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 34,
        "slug": "property-34",
        "title": "Property Title 34",
        "location": "Location 34",
        "price": 44000,
        "bedrooms": 7,
        "bathrooms": 6,
        "area": 9800,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 34.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 35,
        "slug": "property-35",
        "title": "Property Title 35",
        "location": "Location 35",
        "price": 45000,
        "bedrooms": 8,
        "bathrooms": 7,
        "area": 10000,
        "type": "apartment",
        "for_rent": false,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 35.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 36,
        "slug": "property-36",
        "title": "Property Title 36",
        "location": "Location 36",
        "price": 46000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area": 10200,
        "type": "villa",
        "for_rent": true,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 36.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 37,
        "slug": "property-37",
        "title": "Property Title 37",
        "location": "Location 37",
        "price": 47000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area": 10400,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 37.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 38,
        "slug": "property-38",
        "title": "Property Title 38",
        "location": "Location 38",
        "price": 48000,
        "bedrooms": 5,
        "bathrooms": 5,
        "area": 10600,
        "type": "apartment",
        "for_rent": true,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 38.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 39,
        "slug": "property-39",
        "title": "Property Title 39",
        "location": "Location 39",
        "price": 49000,
        "bedrooms": 6,
        "bathrooms": 6,
        "area": 10800,
        "type": "villa",
        "for_rent": false,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 39.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 40,
        "slug": "property-40",
        "title": "Property Title 40",
        "location": "Location 40",
        "price": 50000,
        "bedrooms": 7,
        "bathrooms": 7,
        "area": 11000,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 40.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 41,
        "slug": "property-41",
        "title": "Property Title 41",
        "location": "Location 41",
        "price": 51000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area": 11200,
        "type": "apartment",
        "for_rent": false,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 41.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 42,
        "slug": "property-42",
        "title": "Property Title 42",
        "location": "Location 42",
        "price": 52000,
        "bedrooms": 5,
        "bathrooms": 4,
        "area": 11400,
        "type": "villa",
        "for_rent": true,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 42.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 43,
        "slug": "property-43",
        "title": "Property Title 43",
        "location": "Location 43",
        "price": 53000,
        "bedrooms": 6,
        "bathrooms": 5,
        "area": 11600,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 43.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 44,
        "slug": "property-44",
        "title": "Property Title 44",
        "location": "Location 44",
        "price": 54000,
        "bedrooms": 7,
        "bathrooms": 6,
        "area": 11800,
        "type": "apartment",
        "for_rent": true,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 44.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 45,
        "slug": "property-45",
        "title": "Property Title 45",
        "location": "Location 45",
        "price": 55000,
        "bedrooms": 8,
        "bathrooms": 7,
        "area": 12000,
        "type": "villa",
        "for_rent": false,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 45.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    },
    {
        "id": 46,
        "slug": "property-46",
        "title": "Property Title 46",
        "location": "Location 46",
        "price": 56000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area": 12200,
        "type": "penthouse",
        "for_rent": true,
        "image": "/example1.png",
        "images": ["/example1.png", "/example2.png", "/example3.png"],
        "description": "This is a detailed description for property 46.",
        "features": ["Private Pool", "Garden View", "Maid's Room", "Study Room", "Balcony"],
        "amenities": ["Gym", "Swimming Pool", "Kids Play Area", "BBQ Area", "Security"]
    },
    {
        "id": 47,
        "slug": "property-47",
        "title": "Property Title 47",
        "location": "Location 47",
        "price": 57000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area": 12400,
        "type": "apartment",
        "for_rent": false,
        "image": "/example2.png",
        "images": ["/example2.png", "/example3.png", "/example4.png"],
        "description": "This is a detailed description for property 47.",
        "features": ["Skyline Views", "Rooftop Terrace", "Private Elevator", "Modern Kitchen"],
        "amenities": ["Concierge", "Spa", "24/7 Security", "Kids Club", "Infinity Pool"]
    },
    {
        "id": 48,
        "slug": "property-48",
        "title": "Property Title 48",
        "location": "Location 48",
        "price": 58000,
        "bedrooms": 5,
        "bathrooms": 5,
        "area": 12600,
        "type": "villa",
        "for_rent": true,
        "image": "/example3.png",
        "images": ["/example3.png", "/example4.png", "/example5.png"],
        "description": "This is a detailed description for property 48.",
        "features": ["Sea Views", "Modern Kitchen", "Balcony", "Built-in Wardrobes"],
        "amenities": ["Private Beach Access", "Yacht Club", "Water Sports Facilities", "24/7 Security"]
    },
    {
        "id": 49,
        "slug": "property-49",
        "title": "Property Title 49",
        "location": "Location 49",
        "price": 59000,
        "bedrooms": 6,
        "bathrooms": 6,
        "area": 12800,
        "type": "penthouse",
        "for_rent": false,
        "image": "/example4.png",
        "images": ["/example4.png", "/example5.png", "/example1.png"],
        "description": "This is a detailed description for property 49.",
        "features": ["Golf Course Views", "Wine Cellar", "Spa Room", "Private Elevator"],
        "amenities": ["Golf Club Access", "Tennis Court", "Fitness Center", "24/7 Security"]
    },
    {
        "id": 50,
        "slug": "property-50",
        "title": "Property Title 50",
        "location": "Location 50",
        "price": 60000,
        "bedrooms": 7,
        "bathrooms": 7,
        "area": 13000,
        "type": "apartment",
        "for_rent": true,
        "image": "/example5.png",
        "images": ["/example5.png", "/example1.png", "/example2.png"],
        "description": "This is a detailed description for property 50.",
        "features": ["Smart Home", "High Ceilings", "Floor-to-Ceiling Windows", "Spacious Layout"],
        "amenities": ["Beach Access", "Swimming Pool", "Gym", "24/7 Security"]
    }
]


export async function getProperties() {
    return properties
}

export async function getPropertiesForRentAndSale() {
    // Filter properties for rent (for_rent: true) and limit to 6
    const forRent = properties
        .filter(property => property.for_rent === true)
        .slice(0, 6);

    // Filter properties for sale (for_rent: false) and limit to 6
    const forSale = properties
        .filter(property => property.for_rent === false)
        .slice(0, 6);

    return {
        forRent,
        forSale
    };
}